protected/models/File.php
<?php

/**
 * This is the model class for table "file".
 *
 * The followings are the available columns in table 'file':
 * @property integer $id
 * @property string $label
 * @property string $file_filename
 * @property string $comment
 * @property string $download_name
 */
class File extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'file';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('label, comment, download_name', 'required'),
			array('label, file_filename, download_name', 'length', 'max'=>256),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, label, file_filename, comment, download_name', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'label' => 'Label',
			'file_filename' => 'File Filename',
			'comment' => 'Comment',
			'download_name' => 'Download Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('label',$this->label,true);
		$criteria->compare('file_filename',$this->file_filename,true);
		$criteria->compare('comment',$this->comment,true);
		$criteria->compare('download_name',$this->download_name,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return File the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/FilesController.php
<?php

class FilesController extends AdminBackendController
{
    public function actionIndex()
    {
        $criteria = new CDbCriteria;
        $criteria->order = 'comment ASC';

        $provider = new CActiveDataProvider(
            'FileExt',
            array(
                'criteria' => $criteria,
                'pagination'=>array(
                    'pageSize'=>50,
                ),
            )
        );
        $this->render('index', array('provider' => $provider));
    }

    public function actionCreate()
    {
        $file = new FileExt();
        $this->render('edit', array('model' => $file));
    }

    public function actionUpdate()
    {
        $file = FileExt::model()->findByPk(Yii::app()->request->getParam('id'));
        $this->render('edit', array('model' => $file));
    }

    public function actionDelete()
    {
        FileExt::model()->deleteByPk(Yii::app()->request->getParam('id'));
    }

    public function actionEditable()
    {
        $saver = new TbEditableSaver('FileExt');
        $saver->update();
    }

    public function actionSave()
    {
        $saver = new VMEntitySaver('FileExt');
        $saver->safeSaving = true;

        $saver->afterSave = function(FileExt $model) {
            VMUploadedMediaManager::quickSave($model, 'file');
        };

        $saver->save();
    }
}

protected/views/files/edit.php
<?php
    $form = $this->beginWidget(
        'TbActiveForm',
        array(
            'type' => 'horizontal',
            'htmlOptions' => array('enctype' => 'multipart/form-data'),
            'action' => $this->createUrl('files/save'),
        )
    );
?>

<h1>Добавить / Редактировать файл</h1>

<hr />

<fieldset>
    <?= $form->errorSummary($model); ?>
    <?= $form->textFieldRow($model, 'label', array('hint' => 'Уникальное системное имя (информация для программиста - не менять)', 'class' => 'span4')); ?>
    <?= $form->textFieldRow($model, 'download_name', array('hint' => 'Показывается пользователям в качестве имени загружаемого файла в списке закачек браузера', 'class' => 'span4')); ?>
    <?= $form->textareaRow($model, 'comment', array('hint' => 'Расположение на сайте', 'class' => 'span6', 'rows' => 2, 'style' => 'resize: none')); ?>
    <?= $form->fileFieldRow($model, 'file', array('class' => 'span3')); ?>

    <?= $form->hiddenField($model, 'id'); ?>

    <div class="form-actions">
        <?php
            $this->widget(
                'TbButton',
                array(
                    'buttonType' => 'submit',
                    'type' => 'primary',
                    'label' => 'Сохранить'
                )
            );
        ?>

        <?php
            $this->widget(
                'TbButton',
                array(
                    'buttonType' => 'link',
                    'url' => $this->createUrl('files/index'),
                    'label' => 'Отмена'
                )
            );
        ?>
    </div>
</fieldset>

<?php $this->endWidget(); ?>

protected/views/files/index.php
<div class="pull-right">
    <?php
        $this->widget(
            'TbButton',
            array(
                'label' => 'Добавить файл',
                'type' => 'primary',
                'url' => $this->createUrl('files/create')
            )
        );
    ?>
</div>

<h1>Файлы</h1>

<p>
</p>

<p>
    <?php
        $this->widget(
            'TbGridView',
            array(
                'type' => 'striped bordered condensed',
                'dataProvider' => $provider,
                'template' => "{summary}\n{items}\n{pager}",
                'columns' => array(
                    array(
                        'name' => 'comment',
                        'headerHtmlOptions' => array('class' => 'span5'),
                    ),
                    array(
                        'name' => 'label',
                        'headerHtmlOptions' => array('class' => 'span5'),
                    ),
                    array(
                        'class' => 'TbButtonColumn',
                        'headerHtmlOptions' => array('class' => 'span1'),
                        'template' => '{update}',
                        'buttons' => array(
                            'update' => array(
                                'label' => 'Изменить',
                            ),
                        ),
                    ),
                ),
            )
        );
    ?>
</p>