protected/models/Resident.php
<?php

/**
 * This is the model class for table "resident".
 *
 * The followings are the available columns in table 'resident':
 * @property integer $id
 * @property integer $number
 * @property string $name
 * @property string $short_description
 * @property string $image_filename
 * @property string $occupied_filename
 * @property integer $floor_id
 * @property string $site
 * @property integer $offset_left
 * @property integer $offset_right
 * @property string $region
 *
 * The followings are the available model relations:
 * @property Floor $floor
 */
class Resident extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'resident';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('number, name, short_description, floor_id, offset_left, offset_right, region', 'required'),
			array('number, floor_id, offset_left, offset_right', 'numerical', 'integerOnly'=>true),
			array('name, image_filename, occupied_filename, site', 'length', 'max'=>256),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, number, name, short_description, image_filename, occupied_filename, floor_id, site, offset_left, offset_right, region', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'floor' => array(self::BELONGS_TO, 'Floor', 'floor_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'number' => 'Number',
			'name' => 'Name',
			'short_description' => 'Short Description',
			'image_filename' => 'Image Filename',
			'occupied_filename' => 'Occupied Filename',
			'floor_id' => 'Floor',
			'site' => 'Site',
			'offset_left' => 'Offset Left',
			'offset_right' => 'Offset Right',
			'region' => 'Region',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('number',$this->number);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('short_description',$this->short_description,true);
		$criteria->compare('image_filename',$this->image_filename,true);
		$criteria->compare('occupied_filename',$this->occupied_filename,true);
		$criteria->compare('floor_id',$this->floor_id);
		$criteria->compare('site',$this->site,true);
		$criteria->compare('offset_left',$this->offset_left);
		$criteria->compare('offset_right',$this->offset_right);
		$criteria->compare('region',$this->region,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Resident the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ResidentsController.php
<?php

class ResidentsController extends AdminBackendController
{
    public function actionIndex()
    {
        $criteria = new CDbCriteria;
        $criteria->order = 'number ASC, name ASC';

        $provider = new CActiveDataProvider('ResidentExt');
        $this->render(
            'index',
            array(
                'provider' => $provider,
                'criteria' => $criteria,
            )
        );
    }

    public function actionCreate()
    {
        $resident = new ResidentExt();
        $this->render(
            'edit',
            array(
                'model' => $resident,
                'floors' => CHtml::listData(FloorExt::model()->findAll(), 'id', 'number')
            )
        );
    }

    public function actionUpdate()
    {
        $resident = ResidentExt::model()->findByPk(Yii::app()->request->getParam('id'));
        $this->render(
            'edit',
            array(
                'model' => $resident,
                'floors' => CHtml::listData(FloorExt::model()->findAll(), 'id', 'number')
            )
        );
    }

    public function actionDelete()
    {
        ResidentExt::model()->deleteByPk(Yii::app()->request->getParam('id'));
    }

    public function actionEditable()
    {
        $saver = new TbEditableSaver('ResidentExt');
        $saver->update();
    }

    public function actionSave()
    {
        $saver = new VMEntitySaver('ResidentExt');
        $saver->safeSaving = true;

        $saver->beforeRenderUpdate = function(VMEntitySaver $saver) {
            return array(
                'floors' => CHtml::listData(FloorExt::model()->findAll(), 'id', 'number')
            );
        };

        $saver->afterSave = function(ResidentExt $model) {
            VMUploadedMediaManager::quickSave($model, 'image');
            VMUploadedMediaManager::quickSave($model, 'occupied');
        };

        $saver->save();
    }
}

protected/views/residents/edit.php
<?php
    $form = $this->beginWidget(
        'TbActiveForm',
        array(
            'type' => 'horizontal',
            'htmlOptions' => array('enctype' => 'multipart/form-data'),
            'action' => $this->createUrl('residents/save'),
        )
    );
?>
    <fieldset>
        <legend>Добавить / Редактировать резидента</legend>

        <?= $form->errorSummary($model); ?>
        <?= $form->textFieldRow($model, 'number', array('class' => 'span3')); ?>
        <?= $form->textFieldRow($model, 'name', array('class' => 'span3')); ?>
        <?= $form->textFieldRow($model, 'site', array('class' => 'span3')); ?>
        <?= $form->dropDownListRow($model, 'floor_id', $floors, array('class' => 'span3')); ?>
        <?= $form->textFieldRow($model, 'offset_left', array('class' => 'span3')); ?>
        <?= $form->textFieldRow($model, 'offset_right', array('class' => 'span3')); ?>
        <?= $form->textareaRow($model, 'short_description', array('class'=>'span8', 'rows' => 5)); ?>
        <hr />
        <?= $form->fileFieldRow($model, 'image', array('class' => 'span3')); ?>
        <?= $form->fileFieldRow($model, 'occupied', array('class' => 'span3')); ?>
        <?= $form->textareaRow($model, 'region', array('class'=>'span8', 'rows' => 5)); ?>

        <?= $form->hiddenField($model, 'id'); ?>

        <div class="form-actions">
            <?php
                $this->widget(
                    'TbButton',
                    array(
                        'buttonType' => 'submit',
                        'type' => 'primary',
                        'label' => 'Сохранить'
                    )
                );
            ?>

            <?php
                $this->widget(
                    'TbButton',
                    array(
                        'buttonType' => 'link',
                        'url' => $this->createUrl('residents/index'),
                        'label' => 'Отмена'
                    )
                );
            ?>
        </div>
    </fieldset>
<?php $this->endWidget(); ?>

protected/views/residents/index.php
<div class="pull-right">
    <?php
        $this->widget(
            'TbButton',
            array(
                'label' => 'Добавить резидента',
                'type' => 'primary',
                'url' => $this->createUrl('residents/create')
            )
        );
    ?>
</div>

<h1>Резиденты</h1>

<p>
    <?php
        $this->widget(
            'TbGridView',
            array(
                'type' => 'striped bordered condensed',
                'dataProvider' => $provider,
                'template' => "{summary}\n{items}\n{pager}",
                'columns' => array(
                    array(
                        'name' => 'name',
                        'headerHtmlOptions' => array('class' => 'span3')
                    ),
                    array(
                        'class' => 'VMImagePreviewColumn',
                        'name' => 'image_filename',
                        'headerHtmlOptions' => array('class' => 'span8')
                    ),
                    array(
                        'header' => 'Действия',
                        'class' => 'TbButtonColumn',
                        'headerHtmlOptions' => array('class' => 'span1'),
                        'template' => '{update} {delete}',
                        'buttons' => array(
                            'update' => array(
                                'label' => 'Изменить',
                            ),
                            'delete' => array(
                                'label' => 'Удалить',
                            ),
                        ),
                    ),
                ),
            )
        );
    ?>

</p>