protected/models/Contact.php
<?php

/**
 * This is the model class for table "contact".
 *
 * The followings are the available columns in table 'contact':
 * @property integer $id
 * @property string $label
 * @property string $contact
 * @property string $comment
 */
class Contact extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'contact';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('label, contact, comment', 'required'),
			array('label, contact', 'length', 'max'=>256),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, label, contact, comment', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'label' => 'Label',
			'contact' => 'Contact',
			'comment' => 'Comment',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('label',$this->label,true);
		$criteria->compare('contact',$this->contact,true);
		$criteria->compare('comment',$this->comment,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Contact the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ContactsController.php
<?php

class ContactsController extends AdminBackendController
{
    public function actionIndex()
    {
        $criteria = new CDbCriteria;
        $criteria->order = 'comment ASC';

        $provider = new CActiveDataProvider(
            'ContactExt',
            array(
                'criteria' => $criteria,
                'pagination'=>array(
                    'pageSize'=>50,
                ),
            )
        );
        $this->render('index', array('provider' => $provider));
    }

    public function actionCreate()
    {
        $contact = new ContactExt();
        $this->render('edit', array('model' => $contact));
    }

    public function actionUpdate()
    {
        $contact = ContactExt::model()->findByPk(Yii::app()->request->getParam('id'));
        $this->render('edit', array('model' => $contact));
    }

    public function actionDelete()
    {
        ContactExt::model()->deleteByPk(Yii::app()->request->getParam('id'));
    }

    public function actionEditable()
    {
        $saver = new TbEditableSaver('ContactExt');
        $saver->update();
    }

    public function actionSave()
    {
        $saver = new VMEntitySaver('ContactExt');
        $saver->safeSaving = true;

        $saver->save();
    }
}

protected/views/contacts/edit.php
<?php
    $form = $this->beginWidget(
        'TbActiveForm',
        array(
            'type' => 'horizontal',
            'htmlOptions' => array('enctype' => 'multipart/form-data'),
            'action' => $this->createUrl('contacts/save'),
        )
    );
?>

<h1>Добавить / Редактировать контакт</h1>

<hr />

<fieldset>
    <?= $form->errorSummary($model); ?>
    <?= $form->textFieldRow($model, 'label', array('hint' => 'Уникальное системное имя (информация для программиста - не менять)', 'class' => 'span3')); ?>
    <?= $form->textareaRow($model, 'comment', array('hint' => 'Расположение на сайте', 'class' => 'span6', 'rows' => 2, 'style' => 'resize: none')); ?>
    <?= $form->textFieldRow($model, 'contact', array('hint' => 'Контактная информация', 'class' => 'span3')); ?>

    <?= $form->hiddenField($model, 'id'); ?>

    <div class="form-actions">
        <?php
            $this->widget(
                'TbButton',
                array(
                    'buttonType' => 'submit',
                    'type' => 'primary',
                    'label' => 'Сохранить'
                )
            );
        ?>

        <?php
            $this->widget(
                'TbButton',
                array(
                    'buttonType' => 'link',
                    'url' => $this->createUrl('contacts/index'),
                    'label' => 'Отмена'
                )
            );
        ?>
    </div>
</fieldset>

<?php $this->endWidget(); ?>

protected/views/contacts/index.php
<div class="pull-right">
    <?php
        $this->widget(
            'TbButton',
            array(
                'label' => 'Добавить контакт',
                'type' => 'primary',
                'url' => $this->createUrl('contacts/create')
            )
        );
    ?>
</div>

<h1>Контакты</h1>
<p>
    <b>Телефоны и email - указанные на сайте.</b>
</p>

<p>
    <?php
        $this->widget(
            'TbGridView',
            array(
                'type' => 'striped bordered condensed',
                'dataProvider' => $provider,
                'template' => "{summary}\n{items}\n{pager}",
                'columns' => array(
                    array(
                        'name' => 'comment',
                        'headerHtmlOptions' => array('class' => 'span5'),
                    ),
                    array(
                        'name' => 'label',
                        'headerHtmlOptions' => array('class' => 'span5'),
                    ),
                    array(
                        'name' => 'contact',
                        'headerHtmlOptions' => array('class' => 'span5'),
                    ),
                    array(
                        'header' => 'Действия',
                        'class' => 'TbButtonColumn',
                        'headerHtmlOptions' => array('class' => 'span1'),
                        'template' => '{update}',
                        'buttons' => array(
                            'update' => array(
                                'label' => 'Изменить',
                            )
                        ),
                    ),
                ),
            )
        );
    ?>

</p>